cc_test(
    name = "SpinLockSleepTest",
    srcs = [
        "SpinLockSleepTest.cpp",
    ],
    deps = [
        "//Concurrency:SpinLockSleep",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "ConditionalVariableTest",
    srcs = ["ConditionalVariableTest.cpp"],
    deps = [
        "//Concurrency:ConditionalVariable",
        "@gtest//:gtest_main",
    ],
)
